services:

  app:
    container_name: infobot
    build:
      context: .
      network: host
    restart: always
    command:  ["python", "main.py"]
    env_file:
      - ./.env
    network_mode: host